language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure:  "vqLrAHFlD/eLdn/NlyqMhIrLWl+7fR097Ch/O4etLgFk20+zc0fTyffHoXGbOZQlKwxpS58b2bk7j6S8RJVOv+WSL+lswqk7EBdA+qGmGyad0/K0U9Nz+pK5MfnDFbtXu8ReiH9ompms5rQsGAZ3kMqxlI/5uxh2V290SnjWSxAh4KRqwpZfXycS2oIzWhnZqssGWq/9ZU6TqIsbz+AujmE72iOd75cttg15B56BzgMaPBKdGUOktOEfajVEVDW3bBdFfP1H4Gpg/aO5qaU50g69Qi6FXj72DjyLN/ezfe0QPMbY4XzxkxVQDeoyHG57PpDJBzz7U40qb1nax9NHy5uX/iA3XOQiK8Yl213soUiNrp9RhWDtuWhK/5wbRyOs55D5aUlB5S6MkyEePD/xCuCjdQDn8i53enp68zs8xTGW9AeYf9n2jPPvV06TSue0VQ/+JIN9h8ZhxHt8jhVbGTJFv1p97Q9T3WsgM0Rw86b3sV1uozFqbaLA6szEbZuWhO9tZXGWXSVdf8bmrzUUU5CIQe2y73XQ4Wec0yx4jkgr7hbZUgS16ihgYDF6SBDOLcci1betk9xtRQesyCwwTPRKnYeQptyTp62WMlES/YO02h0CMpsOF75t6UlJycSFjB5WpGqYWMwkgGUIkcVKkx5A4lgkwd1iVKJae+swtYE="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_2155243bff9e_key -iv $encrypted_2155243bff9e_iv -in 077CC9F2.gpg.enc -out 077CC9F2.gpg -d
    - gpg --import 077CC9F2.gpg
install:
    - debuild '-k9D1DC8DD077CC9F2'
deploy:
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      api_key:
          secure: "hB3t5h8JRF3Bem1/2VtSUo5rRQUVkOBLgyf7pVXH2LVQLO89ZhQMQBW0x+hijCzW+I8HnGqEYlkokpH2f0JSqT2fIRRoRKD9EDNC4eamYu9ATgPpcRMF5o3U+5FMKZhH/UC6+7lo2BSd+HP45knVVYfUHJvLxR4TpxnjomIJkldjkndZjQ/SjIjBxaHtwZ7Lw/oppHpKbEEAnuPewivsXfZC7a26kyjtOMFCGzRV+JAO1fCs/hF8npBG3noz2W7vJ1NF5y4MwRlX0+g1czVFTxOQYfefv2BXZA2AaUJf0wdd0DEQ/rmWD8TEQSHsx3iNnNG3QdNrFuD5duqLOu90OeFuruObar7/HpQvx9UBv44uujr/ENbraMvn7yYvcYg+nIuM8njNMJWE6/9vdZQ2Xk/I3zt/H4LntQ3BXkccV/1QR+AasN0aDAs5x6fxX8tEUZShCOX9cVSOYWfAlEG053U5sZZ3o1ufsxfEzJU8osuJcxGQZjP9NPMVaruuw0xYW0fuHra6Zf1+SC14//Ohu5STr2tJauY3U5Vx/7y/Qkp9vBt0Ec4jzLXAZ3mTWAPBqBEyMnrzn5rt4G1ixkgkhELfb8wnK4rK6fGmpOFvNUdLL/Y0hszve3oT+r48AioOxRHqq2EOvqeFAPRzrSJ+1Btm/x4WbNL8Cq6MLwtaOD8="
      on:
          tags: true
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      tag_name: "nightly"
      prerelease: true
      name: Automatic nightly build by Travis on $(date +'%F %T %Z').
      target_commitish: $TRAVIS_COMMIT
      api_key:
          secure: "hB3t5h8JRF3Bem1/2VtSUo5rRQUVkOBLgyf7pVXH2LVQLO89ZhQMQBW0x+hijCzW+I8HnGqEYlkokpH2f0JSqT2fIRRoRKD9EDNC4eamYu9ATgPpcRMF5o3U+5FMKZhH/UC6+7lo2BSd+HP45knVVYfUHJvLxR4TpxnjomIJkldjkndZjQ/SjIjBxaHtwZ7Lw/oppHpKbEEAnuPewivsXfZC7a26kyjtOMFCGzRV+JAO1fCs/hF8npBG3noz2W7vJ1NF5y4MwRlX0+g1czVFTxOQYfefv2BXZA2AaUJf0wdd0DEQ/rmWD8TEQSHsx3iNnNG3QdNrFuD5duqLOu90OeFuruObar7/HpQvx9UBv44uujr/ENbraMvn7yYvcYg+nIuM8njNMJWE6/9vdZQ2Xk/I3zt/H4LntQ3BXkccV/1QR+AasN0aDAs5x6fxX8tEUZShCOX9cVSOYWfAlEG053U5sZZ3o1ufsxfEzJU8osuJcxGQZjP9NPMVaruuw0xYW0fuHra6Zf1+SC14//Ohu5STr2tJauY3U5Vx/7y/Qkp9vBt0Ec4jzLXAZ3mTWAPBqBEyMnrzn5rt4G1ixkgkhELfb8wnK4rK6fGmpOFvNUdLL/Y0hszve3oT+r48AioOxRHqq2EOvqeFAPRzrSJ+1Btm/x4WbNL8Cq6MLwtaOD8="
      on:
          branch: master
before_deploy:
    - >
      if [[ $TRAVIS_BRANCH == "master" ]]; then
        gh release delete nightly -R ${TRAVIS_REPO_SLUG} -y
        git tag -f nightly || true &&
        git remote add gh https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &&
        git push --delete -f gh nightly || true &&
        git push -f gh nightly || true
      fi
