language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure:  "vqLrAHFlD/eLdn/NlyqMhIrLWl+7fR097Ch/O4etLgFk20+zc0fTyffHoXGbOZQlKwxpS58b2bk7j6S8RJVOv+WSL+lswqk7EBdA+qGmGyad0/K0U9Nz+pK5MfnDFbtXu8ReiH9ompms5rQsGAZ3kMqxlI/5uxh2V290SnjWSxAh4KRqwpZfXycS2oIzWhnZqssGWq/9ZU6TqIsbz+AujmE72iOd75cttg15B56BzgMaPBKdGUOktOEfajVEVDW3bBdFfP1H4Gpg/aO5qaU50g69Qi6FXj72DjyLN/ezfe0QPMbY4XzxkxVQDeoyHG57PpDJBzz7U40qb1nax9NHy5uX/iA3XOQiK8Yl213soUiNrp9RhWDtuWhK/5wbRyOs55D5aUlB5S6MkyEePD/xCuCjdQDn8i53enp68zs8xTGW9AeYf9n2jPPvV06TSue0VQ/+JIN9h8ZhxHt8jhVbGTJFv1p97Q9T3WsgM0Rw86b3sV1uozFqbaLA6szEbZuWhO9tZXGWXSVdf8bmrzUUU5CIQe2y73XQ4Wec0yx4jkgr7hbZUgS16ihgYDF6SBDOLcci1betk9xtRQesyCwwTPRKnYeQptyTp62WMlES/YO02h0CMpsOF75t6UlJycSFjB5WpGqYWMwkgGUIkcVKkx5A4lgkwd1iVKJae+swtYE="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_2155243bff9e_key -iv $encrypted_2155243bff9e_iv -in 077CC9F2.gpg.enc -out 077CC9F2.gpg -d
    - gpg --import 077CC9F2.gpg
install:
    - debuild '-k9D1DC8DD077CC9F2'

